# Generated by Django 2.2.12 on 2022-12-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
