# Generated by Django 2.2.12 on 2022-12-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_company_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_img',
        ),
    ]
