# Generated by Django 2.2.12 on 2022-12-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='resume',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
