# Generated by Django 2.2.12 on 2022-12-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_apply_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='resume',
        ),
    ]
