# Generated by Django 2.2.12 on 2022-12-11 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_conversationmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversationMessage',
        ),
    ]
